FROM ubuntu:jammy
RUN apt-get update -y && \
    apt-get install -y curl && \
    # Add nodejs to repo
    curl -sL https://deb.nodesource.com/setup_18.x | bash - && \ 
    # Cleanup packages and update the repos
    apt-get remove -y --purge cmdtest && \
    apt-get update && \
    # Install the packages
    apt-get install -y nodejs && \
    # Smoke tests
    node --version && \
    npm --version && \
    # remove useless files from the current layer
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/lib/apt/lists.d/* && \
    apt-get autoremove && \
    apt-get clean && \
    apt-get autoclean
WORKDIR /app
COPY package.json /app/package.json
RUN npm install && npx playwright install --with-deps chromium
COPY . /app