name: Test local app in a docker container (Playwright)
run-name: Deploy to ${{ github.event.client_payload.sut }} trigger via >${{ github.event_name }}< by @${{ github.actor }}
on:
  push:
    branches:
      - dev
  pull_request:
    branches: [master]
    types: [opened, synchronize]
permissions:
  contents: write
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      # checkout application code
      - name: Checkout project
        uses: actions/checkout@v3
      # build application Docker image
      - name: Build image (application)
        run: docker build -t test-image:latest -f Dockerfile_playwright_official_java .
      # run application Docker image
      - name: Run tests in a container (application)
        run: docker run -i --rm --name test -v /allure-report:/app/allure-report -p 3000:3000 test-image:latest npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 30
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
