name: Test example application
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 19 1 * *'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit message
        env:
          COMMIT_MESSAGE: ${{ toJson(github.event.head_commit.message) }}
        run: echo "$COMMIT_MESSAGE"
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://todo-deployment-pipeline.onrender.com/
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          retry-all: false # Optional, defaults to "false"
