name: Deployment pipeline
run-name: Deploy to ${{ github.event.client_payload.sut }} trigger via >${{ github.event_name }}< by @${{ github.actor }}

on:
  push:
    branches:
      - dev
  pull_request:
    branches: [master]
    types: [opened, synchronize]
permissions:
  contents: write
jobs:
  Simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install && npx playwright install --with-deps chromium
      - name: Check style
        run: npm run lint
      - name: Test
        run: npm run test
  Deployment_to_Render:
    name: Deploy to Render
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: Simple_deployment_pipeline
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false #optional, default true
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URLs one by one sequentially
          url: https://todo-deployment-pipeline.onrender.com/
          follow-redirect: false # Optional, defaults to "false"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          retry-all: false # Optional, defaults to "false"
  Tag_release:
    needs: [Deployment_to_Render]
    if: ${{ github.event_name == 'push' && !contains(join(toJSon(github.event.commits.*.message)), 'skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.65.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          WITH_V: true
          DEFAULT_BUMP: patch
          run: echo "version updated"
  Send_to_Discord:
    needs: [Tag_release]
    runs-on: ubuntu-20.04
    steps:
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Test Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
